### PR TITLE
update to new Knitro.jl's interface

### PR DESCRIPTION
**Pull request by frapac**
KNITRO.jl has been updated to generate the C wrapper automatically with Clang.jl. By doing so, we support all the functions provided in Knitro's C API. However, that comes with a few breaking changes. This PR updates NLPModelsKnitro.jl to support the new version of KNITRO.jl (which should be shipped soon)

### CODE REVIEW

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
Hmm... not sure JSOBot got up this morning...

**Comment by frapac** [comment]
Maybe it's related to the fact that Knitro.jl 0.13.0 has not been released yet?

**Comment by dpo** [comment]
Well, you're right that we should at least wait for that. Still, the bot should try... we'll fix it by the time you release.

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
I retried the tests now that KNITRO 0.13 has been released, but there seems to be an unrelated issue to be fixed here #89

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
So, the tests still fails because JSOBot doesn't rebase with main @MonssafToukal . I tried locally and it passes.

@frapac could you rebase ?

**Pull request merged**
