### PR TITLE
update Jenkinsfile

### PR DESCRIPTION
**Pull request by MonssafToukal**

### CODE REVIEW

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
```
ERROR: LoadError: MethodError: no method matching jac_nln_structure!(::ADNLSModel{Float64, Vector{Float64}}, ::SubArray{Int64, 1, Vector{Int64}, Tuple{UnitRange{Int64}}, true}, ::SubArray{Int64, 1, Vector{Int64}, Tuple{UnitRange{Int64}}, true})
Closest candidates are:
  jac_nln_structure!(!Matched::Union{NLPModelsModifiers.SlackModel, NLPModelsModifiers.SlackNLSModel}, ::AbstractVector{<:Integer}, ::AbstractVector{<:Integer}) at ~/.julia/packages/NLPModelsModifiers/NYaOd/src/slack-model.jl:301
  jac_nln_structure!(!Matched::NLPModelsModifiers.QuasiNewtonModel, ::AbstractVector{<:Integer}, ::AbstractVector{<:Integer}) at ~/.julia/packages/NLPModelsModifiers/NYaOd/src/quasi-newton.jl:105
  jac_nln_structure!(!Matched::NLPModelsModifiers.FeasibilityFormNLS, ::AbstractVector{<:Integer}, ::AbstractVector{<:Integer}) at ~/.julia/packages/NLPModelsModifiers/NYaOd/src/feasibility-form-nls.jl:145
```

We're probably waiting for some of @tmigot's changes to be merged first.

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
I think I fixed it by up to Julia 1.6

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
Hi @MonssafToukal ! The tests pass now.

**Pull request merged**
