### PR TITLE
Move docs to main file

### PR DESCRIPTION
**Pull request by tmigot**
The idea is to build the docstring even KNITRO is not installed properly.

### CODE REVIEW

**Comment by dpo** [comment]
I've been trying to think of a way to do that following a question by @geoffroyleconte. How do you do that though? `using NLPModelsKnitro` must work even if `KNITRO` is not installed. We could use `Requires` but we loose version control.

**Comment by tmigot** [comment]
From the new release of KNITRO, you can do `using KNITRO` now, cf #98

**Comment by dpo** [comment]
We need a similar mechanism in other packages that have a commercial/non-free dependency.

**Comment by tmigot** [comment]
> We need a similar mechanism in other packages that have a commercial/non-free dependency.

Good idea, I will make issues on these packages.

**Comment by tmigot** [comment]
However, I don't understand why the docstring do not show in the references section: [https://juliasmoothoptimizers.github.io/NLPModelsKnitro.jl/previews/PR97/reference/#Reference](https://juliasmoothoptimizers.github.io/NLPModelsKnitro.jl/previews/PR97/reference/#Reference)

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
@JSOBot runtests

**Pull request merged**
