### PR TITLE
Update for KNITRO.jl v0.14.0

### PR DESCRIPTION
**Pull request by odow**
I've been simplifying the C API to KNITRO.jl: https://github.com/jump-dev/KNITRO.jl/issues/267. The main change is to align everything with the underlying C API of Knitro and removing the Julia-specific functions.

The downside is that it introduces a few breaking changes. This PR fixes the tests.

### CODE REVIEW

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
Thanks Oscar! I will merge it when the version 0.14 of KNITRO.jl will be released.

**Comment by odow** [comment]
Can you re-start CI? IT should work now

**Comment by odow** [comment]
How do these tests run if you have the license in the other PR?

**Comment by odow** [comment]
Nice nice nice. This seems like the tests are passing with the new version.

**Pull request merged**
