### PR TITLE
Bump NLPModels

### PR DESCRIPTION
**Pull request by MonssafToukal**
This PR contains the same changes to [this PR](https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/pull/66), but with the necessary files to launch the unit tests via Jenkins.

### CODE REVIEW

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by MonssafToukal** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
Amazing! Thank you!!!

**Pull request merged**
