### PR TITLE
Bump NLPModels 0.18

### PR DESCRIPTION
**Pull request by tmigot**

### CODE REVIEW

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
@JSOBot runtests

**Comment by tmigot** [comment]
@MonssafToukal Any idea why the JSOBot is uploading so many reports?

**Comment by MonssafToukal** [comment]
Because there are 5 opened PRs on this repo and the fix hasn't been done for unit tests.

**Comment by dpo** [comment]
@JSOBot runtests

**Comment by dpo** [comment]
@tmigot We keep getting
```
ERROR: LoadError: MethodError: no method matching ADNLPModels.ForwardDiffAD(::Int64, ::Int64)
```
here.

**Comment by tmigot** [comment]
> @tmigot We keep getting
> 
> ```
> ERROR: LoadError: MethodError: no method matching ADNLPModels.ForwardDiffAD(::Int64, ::Int64)
> ```
> 
> here.

We can actually merge this as the test passes (and I tested locally). 
This is the correct report https://gist.github.com/JSOBot/c03474a7e608e7767e9b3dc76e015edc (note the `NLPModelKNITRO_PR-78` on L.7)
The other reports with this error are the ones from the other PRs.

**Pull request merged**
